[hermes]
lw-pi ansible_host=192.168.0.109 ansible_user=kamil

[homelab]
lw-main ansible_host=192.168.0.105 ansible_user=kamil-rybacki

[builders]
lw-c1 ansible_host=192.168.0.107 ansible_user=kamil ansible_python_interpreter=/usr/bin/python3
