---
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart direct-link-router service
  ansible.builtin.systemd:
    name: "direct-link-router-{{ direct_link_peer_label }}.service"
    state: restarted
