# audiorelay-setup/roles/audiorelay/handlers/main.yml
---
- name: Restart PulseAudio
  ansible.builtin.command: pulseaudio -k
  changed_when: true
  failed_when: false
  become: false

- name: Restart WirePlumber
  ansible.builtin.command: systemctl --user restart wireplumber
  changed_when: true
  failed_when: false
  become: false
