---
distillery_ui_data_dir: /opt/distillery-ui
distillery_ui_port: 8091
distillery_ui_repo: "https://github.com/kamilrybacki/distillery-knowledge-hub.git"
distillery_ui_container_name: distillery-ui
distillery_api_url: "http://192.168.0.107:30800"
distillery_api_key: ""
